### ISSUE TITLE
Sending CREATE operation fails with invalid hex encoding error

### ISSUE THREAD

**Issue by adzialocha** [p2panda/p2panda#381]
When trying to send a CREATE operation the library returns an error using `p2panda-js@0.4.0`. It works when building locally which makes me wonder if something went wrong during the release?

```javascript
const { Session, recoverKeyPair } = require('p2panda-js');

const PRIVATE_KEY = 'e0a2202cc2349c2e1f95b6718265dd71c6557b3a94e1ff66696d24af206e3d42';

async function run() {
  const session = new Session('http://localhost:2020/graphql');
  const keyPair = await recoverKeyPair(PRIVATE_KEY);
  session.setKeyPair(keyPair);

  await session.create({
    name: 'message',
    type: 'str',
  }, { schema: 'schema_field_definition_v1' });
}

run();
```

.. fails with error:

```
/home/adz/dev/demo/node_modules/p2panda-js/lib/wasm/index.js:702
    var ret = new Error(getStringFromWasm0(arg0, arg1));
              ^

Error: invalid hex encoding in hash string
    at module.exports.__wbg_new_342a24ca698edd87 (/home/adz/dev/demo/node_modules/p2panda-js/lib/wasm/index.js:702:15)
    at wasm://wasm/0034f07a:wasm-function[846]:0xb0f56
    at wasm://wasm/0034f07a:wasm-function[144]:0x7c96d
    at wasm://wasm/0034f07a:wasm-function[417]:0xa4fc7
    at module.exports.encodeCreateOperation (/home/adz/dev/demo/node_modules/p2panda-js/lib/wasm/index.js:172:14)
    at /home/adz/dev/demo/node_modules/p2panda-js/lib/index.js:1405:30
    at step (/home/adz/dev/demo/node_modules/p2panda-js/lib/index.js:1341:17)
    at Object.next (/home/adz/dev/demo/node_modules/p2panda-js/lib/index.js:1272:14)
    at fulfilled (/home/adz/dev/demo/node_modules/p2panda-js/lib/index.js:1226:24)
```

**Comment by adzialocha** [comment]
Something must have went wrong when publishing that release, not sure how it happened though .. I think we can fix this by making a proper build next time.
